name: Matrix strategy with same data
on: workflow_dispatch
jobs:
  matrix-job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [14, 16]
        include:
          - os: macos-latest
            node: 18
          - os: ubuntu-latest
            node: 19

    steps:
      - run: echo "Hello ${{ matrix.os }} ${{ matrix.node }}"