name: Use Github API to get workflows id and logs
on: workflow_dispatch
jobs:
    get_workflows_id:
        runs-on: ubuntu-latest
        steps:
        -   name: Get workflows id
            run: |
                echo "Get workflows id"
                curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows | jq '.workflows[] | {id, name}'
    get_workflow_logs:
        runs-on: ubuntu-latest
        needs: get_workflows_id
        steps:
        -   name: Get workflow logs
            run: |
                echo "Get workflow logs"
                curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ needs.get_workflows_id.outputs.id }}/logs | jq '.logs[] | {name, url}'