name: Publish to GitHub Packages

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Chequear código
        uses: actions/checkout@v4

      - name: Configurar Java y Maven
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'maven'
          server-id: github              # Debe coincidir con <id> en pom.xml
          server-username: ${{ github.actor }}
          server-password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publicar paquete
        working-directory: ./package_maven
        run: mvn deploy -DskipTests