name: Approval Workflow
on: [workflow_dispatch, push]
jobs:
    hello-world-job:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Hello World
              run: echo "Hello, world!"
