name: Types of inputs in workflow_dispatch
on:
  workflow_dispatch:
    inputs:
      environment_input:
        description: 'An environment input'
        required: true
        default: 'production'
      string_input:
        description: 'A string input'
        required: true
        default: 'default_string'
      boolean_input:
        description: 'A boolean input'
        required: true
        default: 'false'
      choice_input:
        description: 'A choice input'
        required: true
        type: choice
        default: 'option1'
        options:
          - option1
          - option2
          - option3
      number_input:
        description: 'A number input'
        required: true
        default: '42'
jobs:
    example_job:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment_input }}
        steps:
            - name: Print inputs
              run: |
                echo "String input: ${{ github.event.inputs.string_input }}"
                echo "Boolean input: ${{ github.event.inputs.boolean_input }}"
                echo "Choice input: ${{ github.event.inputs.choice_input }}"
                echo "Environment input: ${{ github.event.inputs.environment_input }}"
                echo "Number input: ${{ github.event.inputs.number_input }}"