name: Test execute of jobs
on: workflow_dispatch
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: job-1
              run: echo "Job 1"
    job2:
        runs-on: ubuntu-latest
        needs: job1
        steps:
            - name: job-2
              run: echo "Job 2"
    job3:
        runs-on: ubuntu-latest
        if: ${{ always() }}
        needs: [job1, job2]
        steps:
            - name: job-3
              run: echo "Hello, galaxy!"