#Create a workflow that demonstrates the output structure of a job
name: Output Structure Example
on: workflow_dispatch
jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      name: example_output
      description: 'An example output'
      value: ${{ steps.example_step.outputs.example_output }}
    steps:
      - name: Example Step
        id: example_step
        run: echo "example_output=Hello, world!" >> $GITHUB_OUTPUT
  another_job:
    runs-on: ubuntu-latest
    needs: example_job
    steps:
      - name: Use Output
        run: echo "Deploying version ${{ needs.example_job.outputs.example_output }}"