name: Show default environment variables
on: workflow_dispatch
jobs:
    show_env_vars:
        runs-on: ubuntu-latest
        steps:
        -   name: Show default environment variables
            run: |
                echo "Default environment variables:"
                env
                echo "GITHUB_ENV:"
                echo $GITHUB_ENV
                echo "GITHUB_PATH:"
                echo $GITHUB_PATH
                echo "GITHUB_OUTPUT:"
                echo $GITHUB_OUTPUT
                echo "RUNNER_OS:"
                echo $RUNNER_OS