name: Use encrypted secrets in if conditionally
on: workflow_dispatch
env:
  MY_SECRET_VAR: ${{ secrets.MY_SECRET }}

jobs:
    develop-build:
        if: github.repository == 'joseaxity/practice_certification_ga'
        runs-on: ubuntu-latest
        steps:
        -   name: This will not fail
            if: env.MY_SECRET_VAR != ''
            run: echo "Secret exists"
    develop-deploy:
        needs: develop-build
        runs-on: ubuntu-latest
        steps:
        -   name: This will fail
            if: env.MY_SECRET_VAR != ''
            run: echo "Secret exists"