name: Matrix example
on: [push, workflow_dispatch]
jobs:
    matrix-job:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                pet: [cat, dog]
                color: [pink, brown]
                include:
                    - color: white
                      pet: dog
        steps:
            -   name: Run a script
                run: echo "This is a matrix job with pet ${{ matrix.pet }} and color ${{ matrix.color }}"