name: Secrets example
on: [push, workflow_dispatch]
env:
    MY_SECRET: ${{ secrets.MY_SECRET }}
jobs:
    secret-job:
        runs-on: ubuntu-latest
        steps:
            -   name: Run a script
                run: echo "This is a job with secret ${{ env.MY_SECRET }}"