name: Publish to GHCR
on:
    push:
        branches: [main]
        paths:
            - docker_github/** # Only run if changes are made in the docker_github directory
            
jobs:
    publish:        
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GH_TOKEN }}

            #lower case ${{ github.repository }}
            - name: Lowercase repository name
              run: |
                # Convert the repository name to lowercase
                REPOSITORY_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
                echo "$REPOSITORY_NAME"
                echo "REPOSITORY_NAME=$REPOSITORY_NAME" >> $GITHUB_ENV

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: docker_github/
                  push: true
                  tags: ghcr.io/${{ env.REPOSITORY_NAME }}/my-image:${{ github.sha }}