name: Default values
on: #[push, 
    workflow_dispatch:

jobs:
    validate-secret:
        runs-on: ubuntu-latest
        env:
            super_secret: ${{ secrets.Supersecret }}
            repo: $GITHUB_REPOSITORY
        defaults:
            run:
                shell: bash
                working-directory: .
        steps:
            - if: ${{ env.super_secret != '' }}
              run: echo "Supersecret is set"
            - if: ${{ env.super_secret == ''}}
              run: echo "Supersecret is not set"
            - run: echo "This is way 1 a default $repo value"
            - run: echo "This is way 3 default ${{ env.repo }} value"
