name: Failure with contidions
on: #push
  workflow_dispatch:
    
jobs:
  failure_conditions:
    runs-on: ubuntu-latest
    steps:
      - name: Check name repository
        if: ${{ github.repository == 'JoseAxity/practice_certification_ga' }}
        run: echo "The name of the repository is ${GITHUB_REPOSITORY}"
      - name: Check name repository 2
        if: github.repository == 'JoseAxity/practice_certification_ga'
        run: echo "The name of the repository is ${GITHUB_REPOSITORY}"
      - name: Failing step
        id: demo
        run: exit 1
      - name: The demo step has failed
        if: always() && steps.demo.outcome == 'failure'
        run: |
          echo "The job has outcome ${{steps.demo}}"
          echo "The job has conclusion ${{steps.demo.conclusion}}"