name: Scheduler by 10 minute
on:
    schedule:
        - cron: '*/10 * * * *' # Every minute
    workflow_dispatch:
jobs:
    scheduler:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Run a script
              run: echo "This is a scheduled workflow that runs every minute."